version: '3.7'

services:
  web:
    image: tariqyousef/sumviz_web_interface
    command: gunicorn SumViz.wsgi:application  --bind 0.0.0.0:8000 
    volumes:
      - static_volume:/usr/src/sumviz/static/
      - ./data/:/usr/src/sumviz/data/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
      - ./.env.db
    shm_size: '2gb'
    restart: always

    
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/sumviz/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: